In [90]:
import pandas as pd
from sklearn.datasets import load_digits
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression

In [91]:
digits  = load_digits()

In [92]:
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.33, random_state=42)

In [93]:
lr = LogisticRegression(max_iter = 7600)
lr.fit(X_train, y_train)
lr.score(X_test,y_test)

0.9730639730639731

In [94]:
sv = SVC()
sv.fit(X_train, y_train)
sv.score(X_test,y_test)

0.9865319865319865

In [95]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
rf.score(X_test,y_test)

0.9764309764309764

In [96]:
"created function to run diffrent model to get score"
def get_score(model,X_train, y_train,X_test,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [97]:
get_score(lr,X_train,y_train,X_test,y_test)

0.9730639730639731

In [98]:
digits.target.shape

(1797,)

In [99]:
digits.data.shape

(1797, 64)

In [100]:
" this works better than train_test_split"
"this also split the o/p values using given n_split "
"this works better on ramdom output values"
from sklearn.model_selection import KFold

In [101]:
fold = KFold(n_splits=3)

In [102]:
import numpy as np

In [103]:
lr_score = []
sv_score = []
rf_score = []


In [104]:
"created for loop to get the average score from diffent model"
for train_index, test_index in fold.split(digits.data, digits.target):
    X_train,X_test = digits.data[train_index], digits.data[test_index]
    y_train,y_test = digits.target[train_index], digits.target[test_index]
#     print(X_train.shape)
#     print(X_test.shape)
#     print(y_train.shape)
#     print(y_test.shape)
    
    lr_score.append(get_score(lr,X_train,y_train,X_test,y_test))
    sv_score.append(get_score(sv,X_train,y_train,X_test,y_test))
    rf_score.append(get_score(rf,X_train,y_train,X_test,y_test))
    

In [105]:
np.mean(lr_score)

0.9287701725097385

In [106]:
np.mean(sv_score)

0.9677239844184752

In [107]:
np.mean(rf_score)

0.9343350027824151

In [108]:
"this works better on iris data o/p values(0,0,0,1,1,1,2,2,2)"
from sklearn.model_selection import StratifiedKFold

In [109]:
kf = StratifiedKFold(n_splits=2)

In [110]:
lr_score = []
sv_score = []
rf_score = []


In [111]:
for train_index, test_index in kf.split(digits.data, digits.target):
    X_train,X_test = digits.data[train_index], digits.data[test_index]
    y_train,y_test = digits.target[train_index], digits.target[test_index]
#     print(X_train.shape)
#     print(X_test.shape)
#     print(y_train.shape)
#     print(y_test.shape)
    
    lr_score.append(get_score(lr,X_train,y_train,X_test,y_test))
    sv_score.append(get_score(sv,X_train,y_train,X_test,y_test))
    rf_score.append(get_score(rf,X_train,y_train,X_test,y_test))
    

In [112]:
np.mean(lr_score)

0.9215423719995739

In [113]:
np.mean(sv_score)

0.9571523419984096

In [114]:
np.mean(rf_score)

0.9254337286418217

In [116]:
'in this we can do model fitting and get score  using all hyper tuning parameter'
from sklearn.model_selection import cross_val_score

In [117]:
cross_val_score(LogisticRegression(max_iter=7600), digits.data,digits.target, cv = 5)

array([0.925     , 0.87777778, 0.93871866, 0.93314763, 0.89693593])

In [118]:
cross_val_score(SVC(), digits.data,digits.target, cv = 5)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [119]:
cross_val_score(RandomForestClassifier(), digits.data,digits.target, cv = 5)

array([0.92777778, 0.91388889, 0.9637883 , 0.97214485, 0.92479109])

In [121]:
cross_val_score(SVC(C= 10), digits.data,digits.target, cv = 5)

array([0.98055556, 0.95833333, 0.98328691, 0.98885794, 0.95821727])